apiVersion: v1
description: A Helm chart for the Kamino vmss-prototype pattern image generator
name: vmss-prototype
version: 0.0.1
maintainers:
  - name: Michael Sinz
    email: msinz@microsoft.com
home: https://speechwiki.azurewebsites.net/architecture/skyman-vmss-prototype-pattern.html
sources:
  - https://github.com/Michael-Sinz/kamino
keywords:
  - vmss
  - azure
  - kubernetes
  - kamino
